cloud:
  aws:
    credentials:
      access-key: AKIAXXPMYVOG5N5E2AVI
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: gofortraining-test


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB